version: "3.7"
services:

  bot:
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    networks:
      - shortcut
    depends_on:
      - db
      - redis

  db:
    image: postgres:12-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432
      - "25000:5432"  # For windows users if can't connect to DataGrip.
    volumes:
      - pgsql-volume:/var/lib/postgresql/data:delegated
    networks:
      - shortcut

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis-volume:/data
    networks:
      - shortcut

  workercheck:
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - WORKER=workerCheck
    networks:
      - shortcut
    depends_on:
      - db
      - redis

volumes:
  pgsql-volume:
  redis-volume:

networks:
  shortcut:
    driver: bridge
