name: Docker CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1

      - name: Login to DockerHub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          push: true
          tags: justapassenger/snail-bot:latest
          build-args: |
            Token=${{ secrets.BOT_TOKEN }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
