name: Node.js CI with TypeScript

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Check-out
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - name: Setting up the dummy configs
      run: cp src/config/auth.template.json src/config/auth.json && cp src/config/config.template.json src/config/config.json

    - name: ESLint
      uses: iCrawl/action-eslint@v1

    - name: Run TypeScript compiler
      run: tsc --diagnostics
